spring:
  application:
    name: ordem-servico-api
  datasource:
    url: jdbc:postgresql://localhost:5432/ordem_servico_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

server:
  port: 8080

app:
  security:
    jwt:
      secret: "uma-chave-secreta-local-com-pelo-menos-32-caracteres"
      expiration-minutes: 120
